exclude: |
  (?x)^(
    code/data-landing-zone/README.md|
    code/data-management-zone/README.md
  )$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-json
    - id: check-yaml
    - id: pretty-format-json
      args: ["--indent", "2", "--autofix", "--no-sort-keys"]
