repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-json
    - id: check-yaml
    - id: pretty-format-json
      args: ["--indent", "2", "--autofix", "--no-sort-keys"]
- repo: https://github.com/terraform-docs/terraform-docs
  rev: v0.16.0
  hooks:
    - id: terraform-docs-go
      args: ["-c", "./.terraform-docs.yml", "./code/data-management-zone"]
    - id: terraform-docs-go
      args: ["-c", "./.terraform-docs.yml", "./code/data-landing-zone"]
- repo: local
  hooks:
    - id: terraform-fmt
      name: terraform fmt
      description: runs terraform fmt
      entry: terraform fmt -recursive
      language: system
      pass_filenames: false
