formatter: "markdown document"

version: "0.16.0"

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |
  {{ .Header }}

  ## Documentation
  <!-- markdownlint-disable MD033 -->

  {{ .Requirements }}

  {{ .Modules }}

  <!-- markdownlint-disable MD013 -->
  <!-- markdownlint-disable MD034 -->
  {{ .Inputs }}

  {{ .Outputs }}

  <!-- markdownlint-enable -->
  {{ .Footer }}

output:
  file: "README.md"
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
