name: "Feature Request & Ideas 🚀"
description: Suggest a new feature or improvement (this does not mean you have to implement it)
title: "Feature: "
labels:
  - feature
  - backlog
assignees: "marvinbuss"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!

  - type: textarea
    id: feature_description
    attributes:
      label: Feature or Idea - What?
      placeholder: Briefly describe what the new feature, idea or enhancement entails.
    validations:
      required: true

  - type: textarea
    id: feature_reason
    attributes:
      label: Feature or Idea - Why?
      placeholder: Briefly describe why the new feature, idea or enhancement is required and what outcome you are trying to achieve.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "Thanks for completing this form!"
