name: Terraform Docs Template

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
        description: "Specifies the working directory."

permissions:
  pull-requests: write

jobs:
  deployment:
    name: Terraform Lint
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v3

      # Generate Terraform Docs
      - name: Render Terraform Docs
        id: terraform_docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          config-file: ".terraform-docs.yml"
          working-dir: ${{ inputs.working_directory }}
          git-push: "true"
          git-push-user-name: "github-actions[bot]"
          git-push-user-email: "github-actions[bot]@users.noreply.github.com"
          git-commit-message: "terraform-docs: automated action"
          git-push-sign-off: "false"
