name: Data Landing Zone Deployment
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "code/data-landing-zone/**"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "code/data-landing-zone/**"

jobs:
  terraform_lint:
    uses: ./.github/workflows/_terraformLintTemplate.yml
    name: "Terraform Lint"
    with:
      terraform_version: "1.4.6"
      working_directory: "./code/data-landing-zone"

  terraform_plan_dev:
    uses: ./.github/workflows/_terraformPlanTemplate.yml
    name: "Terraform Plan"
    needs: [terraform_lint]
    with:
      environment: "dev"
      terraform_version: "1.4.6"
      working_directory: "./code/data-landing-zone"
    secrets:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

  # terraform_apply_dev:
  #   uses: ./.github/workflows/_terraformApplyTemplate.yml
  #   name: "Terraform Apply"
  #   needs: [terraform_plan_dev]
  #   if: github.event_name == 'push' || github.event_name == 'release'
  #   with:
  #     environment: "dev"
  #     terraform_version: "1.4.6"
  #     working_directory: "./code/data-landing-zone"
  #   secrets:
  #     TENANT_ID: ${{ secrets.TENANT_ID }}
  #     CLIENT_ID: ${{ secrets.CLIENT_ID }}
  #     CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  #     SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
