name: Dev Deployment
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "code/**"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "code/**"

jobs:
  azure:
    uses: ./.github/workflows/_azureTemplate.yml
    name: "Connect to Azure"
    with:
      environment: "dev"
    secrets:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
